version: '3.9'


services:
  aiogram:
    build: ./
    container_name: waw_telebot
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.2-alpine
    container_name: waw_postgres
    restart: always
    env_file:
      - .env

  redis:
    image: redis:7.2.4-alpine
    container_name: waw_redis
    restart: always
    env_file:
      - .env

  adminer:
    image: adminer:latest
    container_name: waw_adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
